config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'lyrics/index'
  root to: "lyrics#index"
  resources :lyrics, only: %i[index new create show]
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lyric.rb
class Lyric < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :lyric, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lyrics
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/lyrics_controller.rb
class LyricsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  def index
    @lyric = Lyric.includes(:user)
  end

  def new
    @lyric = Lyric.new
  end

  def create
    @lyric = Lyric.new(lyric_params)
    if @lyric.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  private

  def lyric_params
    params.require(:lyric).permit(:title, :lyric).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @name = current_user.name
    @lyrics = current_user.lyrics
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoundLyric</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lyrics/index.html.erb
<div class= "title_contents">

  <ul class='lists-right'>
    <li><%= link_to "sound lyric", new_lyric_path, class:"sound_lyric" %></li>

      <% if user_signed_in? %>
        <li><%= link_to current_user.name, user_path(current_user.id), class: "user-name" %> </li>
        <li><%= link_to "ログアウト", destroy_user_session_path, class: "logout"  %> </li>
        <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
  </ul>

  </div>

app/views/lyrics/new.html.erb
<div class= "title_contents">

  <div class= "page_title">new lyric </div>

  <div class= "lyric_contents">

  <%= form_with model: @lyric, local: true do |f| %>   

    <div class= "page_title"> 
      title
    </div>
    <div>
      <%= f.text_field :title, class:"lyric_title", id:"lyric_title" %>
    </div>

    <div class= "page_title"> 
      lyrics
    </div>
    <div>
      <%= f.text_area :lyric, class:"lyrics", id:"lyrics", placeholder: "歌詞を書く..." %>
    </div>
    <div class="post-btn-contents">
      <%= f.submit "投稿する" ,class:"post-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <% end %>

  </div>

</div>

app/views/users/show.html.erb
<div class="title_contents">

  <div class="contents-row">
    <h1><%= link_to @name, root_path, class:"contents-row"%>さんの歌詞一覧</h1>
    <% @lyrics.each do |lyric| %>
      <div class="page_title">[title]</div>
        <div class="page_title"><%= lyric.title %></div>
      <div class="page_title">[lyric]</div>
        <div class="page_title"><%= lyric.lyric %></div>
      </div>
    <% end %>
  </div>

</div>